### ISSUE TITLE
I have a trouble

### ISSUE THREAD

**Issue by fajarwahyu99** [BadChoice/handesk#105]
![image](https://user-images.githubusercontent.com/11350854/37260304-1a736b1a-25c4-11e8-98ca-d44190ae1175.png)

How to solve di problem?

thank you

**Comment by BadChoice** [comment]
Can you try dev branch and see if it still happens there?

**Comment by AdelBarham2017** [comment]
just run "composer update" from the command line

**Comment by fajarwahyu99** [comment]
What the username and password for login?

**Comment by BadChoice** [comment]
@fajarwahyu99 you can find them in the readme
