### ISSUE TITLE
Can't login with the default credential

### ISSUE THREAD

**Issue by SBA18** [BadChoice/handesk#107]
Hi,

I set up all steps, but I can't login using default login and password generated in the user factory.

I'm using the dev branch and tested the v1.3.3. And password reset link don't work.

**Comment by BadChoice** [comment]
Did you do the artisan:migrate and db:seed?

**Comment by SBA18** [comment]
Yes, I'm a Laravel developer and others frameworks. All steps is respected but nothing happen for login. I will investigate later, if I found bugs I will report you back.

**Comment by SBA18** [comment]
Looked deep and it work, Before I'm looking the factory and the password was secret. But you put the admin on Database Seeder registry.
