### ISSUE TITLE
Problems with .env configuration

### ISSUE THREAD

**Issue by bitcoinshirt** [BadChoice/handesk#115]
I've been trying to configure the helpdesk ticket, but I'm unable to see any emails in my handesk after configuration. 
Here are my installation steps :

1.  I used softaculous deployment to set server up as a support.mysite.com
2.  Edited the .env configuration 

```
MAIL_DRIVER=smtp
MAIL_HOST=localhost
MAIL_PORT=25
MAIL_USERNAME=support@mysite.com
MAIL_PASSWORD=passtest
MAIL_ENCRYPTION=null

MAIL_FETCH_HOST=localhost
MAIL_FETCH_PORT=110
MAIL_FETCH_USERNAME=support@mysite.com
MAIL_FETCH_PASSWORD=passtest
MAIL_FETCH_OPTIONS=/pop3
// for options check https://secure.php.net/manual/de/function.imap-open.php

```
3. When I send the email to support@mysite.com nothing happens. I've sent a dozen of test emails from various email providers, but the tickets are not created.

Have I overlooked something in .env or I missed a configuration step? My understanding is that from now on each email sent to support@mysite.com will create a ticket in handesk. If there's any more details I should provide, please tell me. 

I love the interface and the idea behind the project. Thank you.

**Comment by BadChoice** [comment]
You need to add the cron so mails are fetched every minute

It is in the docs as well, you can also run it manually with 

‘php artisan handesk:fetchNewEmails’

Can’t remember the exact command but artisan will tell you if you write it wrong ;)

Jordi Puigdellívol

El 2 abr 2018, a les 10:02, bitcoinshirt <notifications@github.com> va escriure:

**Comment by bitcoinshirt** [comment]
@BadChoice Thanks for the quick reply. Does this mean that current setup does not fetch emails at all or fetches them at certain intervals? I'm not sure if my shared hosting plan allows the cron every minute, but I will try it. 

Thank you.

**Comment by BadChoice** [comment]
Exactly, the installation alone does not fetch the emails, but you can update the scheduler to run any other interval as your hosting can allow you

I don’t know any other way to fetch the emails periodically without a cron, 

do you have any other idea?

Jordi Puigdellívol

El 2 abr 2018, a les 10:30, bitcoinshirt <notifications@github.com> va escriure:

**Comment by bitcoinshirt** [comment]
Our hosting actually allowed fetching for every 30min, so that solved the issue, thanks a lot.

**Comment by BadChoice** [comment]
Great! I happy to hear it ;)
