### ISSUE TITLE
"view the ticket in Handesk" - Create an account for customers automatically and allow link to be disabled

### ISSUE THREAD

**Issue by bitcoinshirt** [BadChoice/handesk#117]
Right now when the ticket is submitted, when customer clicks on a  "view the ticket in Handesk" it redirects them to a login page. But it's not clear if they should register and how. 

I propose two solutions :
1. Create an account and password automatically
2. Allow us to disable viewing tickets

What do you think? I think if someone would like to view the ticket on the handesk, it's really confused on how they should register.

**Comment by BadChoice** [comment]
There is a public link for the ticket, that it is the one the customer should see (it creates a random hash for it) so for example

`handesk.io/tickets/AFHKS234`

And this is the link they should receive, which doesn't require the login,

I'll make sure the right one is sent..

**Comment by bitcoinshirt** [comment]
Ah that now makes quite a lot of sense, would solve an issue.

By the way thanks for creating the handesk, I love it. It's absolutely the best ticket project. Perhaps have a slack community where we can communicate and improve it together.

**Comment by BadChoice** [comment]
Sound as a great idea!
If you want, you can go ahead and create it :D

**Comment by bitcoinshirt** [comment]
@BadChoice Done, https://handesk.slack.com/ I'll add you as a workspace owner once you sign up.

**Comment by bitcoinshirt** [comment]
After doing changes in #113 this has been resolved as well.
