### ISSUE TITLE
Gmail failed to authenticate 

### ISSUE THREAD

**Issue by bitcoinshirt** [BadChoice/handesk#118]
Is email supposed to look like this?

from: | Customer John <customerjohnexample@gmail.com>
-- | --
reply-to: | support@mysite.com
to: | customerjohnexample@gmail.com

It appears that John is sending email to himself? There's also a gmail warring about[ message authentication failure. 
](https://support.google.com/mail/answer/180707?visit_id=1-636583516381302496-3958417680&p=email_auth&hl=en&rd=1)

![2018-04-03_13-30-39](https://user-images.githubusercontent.com/36959754/38246843-9ba026fe-3732-11e8-81d9-df2bea4f7fbf.jpg)

**Comment by BadChoice** [comment]
you can update the from and to from your .env file so it is what will appear,
if the smtp you are using is not in the same domain that the domain of the sender email the appears the auth thing I believe

The `to` should be the email of who it is notification (the receiver) the from, should be your site (as defined in .env)

**Comment by bitcoinshirt** [comment]
So my hosting set it up this way, is this okay, or should I change something?

MAIL_DRIVER=smtp
MAIL_HOST=localhost
MAIL_PORT=25
MAIL_USERNAME=support@mydomain.com
MAIL_PASSWORD=mypassword
MAIL_ENCRYPTION=null

MAIL_FETCH_HOST=localhost
MAIL_FETCH_PORT=110
MAIL_FETCH_USERNAME=support@mydomain.com
MAIL_FETCH_PASSWORD=mypassword
MAIL_FETCH_OPTIONS=/pop3

**Comment by BadChoice** [comment]
I believe the mail_host=localhost might be the problem as localhost is not the same as @mydomain.com
