### ISSUE TITLE
Getting 500 Internal Server Error when trying to view the attachement in the ticket

### ISSUE THREAD

**Issue by bitcoinshirt** [BadChoice/handesk#119]
When a customer attaches an image, when trying to view the attachment, I'm getting 500 internal server error message.

The attachment appears in this folder mysite/storage/attachments/9_tickets.PNG

Is this a something on my end?

**Comment by BadChoice** [comment]
Make sure you have write permissions on storage and the folder storage/attachments is created

**Comment by bitcoinshirt** [comment]
Makes sense, upon checking while I do have /storage folder I don't have the /attachments inside the /storage. Should I just create the empty folder called "attachments" and give write permissions to it and give same permission to an entire storage folder?

![screenshot from 2018-04-03 17-59-05](https://user-images.githubusercontent.com/36959754/38260762-fa6f192c-3757-11e8-967d-5b9a722898fd.png)

**Comment by BadChoice** [comment]
Yes, create the folder and give write permissions, that should be enough

**Comment by bitcoinshirt** [comment]
Okay, I created the "attachments" inside /storage. I set the permission 7 7 7 to both storage and 
attachments folders. 

![screenshot from 2018-04-04 00-48-59](https://user-images.githubusercontent.com/36959754/38279831-aeb5968e-3791-11e8-8015-03b72169359d.png)


1. Is 7 7 7 a proper permission?
2. When I try to upload an attachment as a reply to a customer, I get the following error :  
```
 (1/1) ErrorException

Trying to get property 'id' of non-object
in Attachment.php (line 17)
at HandleExceptions->handleError(8, 'Trying to get property \'id\' of non-object', '/home/site/public_html/mysite.co/support/app/Attachment.php', 17, array('request' => object(Request), 'attachable' => null))in Attachment.php (line 17)
``` 
The error is quite long, [here's an entire error on pastebin.](https://pastebin.com/jfAtXXct)

**Comment by BadChoice** [comment]
Line 17 is as follows

`$path = str_replace(' ', '_', $attachable->id.'_'.$request->file('attachment')->getClientOriginalName());`

and it days the $attachable has no id (the attachable is the comment itself)

I believe the error might come from a previous place.. if there is no attachment, the comment is created correctly?

**Comment by bitcoinshirt** [comment]
My particular issue was solved with symlinks

The following symlink had to be created inside the storage/ directory.

attachments --> app/public/attachments

The symlink was created with the following command.
Code:
`myadmin@myemail.com [mydomaint/storage]# ln -s app/public/attachments attachments`
