### ISSUE TITLE
New ticket notification emails

### ISSUE THREAD

**Issue by nowtech42** [BadChoice/handesk#125]
I do not receive any new ticket notification emails. If I assign a ticket, I get that notification. Is it possible to auto assign new tickets? Or how do I enable notifications on new tickets?

**Comment by BadChoice** [comment]
Hi
There is the notification settings in your account section, you can enable/disable the ones you want

**Comment by nowtech42** [comment]
Yes, I have them all checked

**Comment by BadChoice** [comment]
How do you create the ticket?
If you create a new ticket from handesk itself you won't receive a notification (as you created it)
To auto assign new tickets, you just need to update the status and if the ticket is not assigned it will automatically auto assign to you
