### ISSUE TITLE
What is requester? 

### ISSUE THREAD

**Issue by kvlknctk** [BadChoice/handesk#143]
What we need to use for requester area? I just want to make a ticket for a certain group. I can not find the document for Handesk.
Thnx. 

![resim](https://user-images.githubusercontent.com/10873815/40558153-1c3a430c-605b-11e8-9f04-ab7d436c2dfa.png)

**Comment by Nevvalife** [comment]
Hi friend, I think some of them will help you 
#seker.bank.com.tr.#ez#tennım

**Comment by BadChoice** [comment]
Hi, the requesters is the person who starts the ticket
it is automatically filled up when it comes by email or api, but if you are creating a ticket yourself, it is like yo got a phone call or something, so you add the requester information there
