### ISSUE TITLE
A non well formed numeric value encountered

### ISSUE THREAD

**Issue by abahagt** [BadChoice/handesk#144]
(2/2) ErrorException
A non well formed numeric value encountered (View: /home/user/public_html/resources/views/reports/index.blade.php)
in KpiRepository.php line 86 when i open reports link

please fix it thanks

**Comment by BadChoice** [comment]
This is not happening to me, can you send me a dump of you kpis tables to see if I can make it happen on my side?
Thanks!

**Comment by abahagt** [comment]
The problem has been solved Thank you for your interest
