### ISSUE TITLE
Whoops, looks like something went wrong.

### ISSUE THREAD

**Issue by AugmentBLU** [BadChoice/handesk#145]
Hello,

I've just installed the latest version on Laravel Forge, it installed fine - however, when I create a new ticket I get `Whoops, looks like something went wrong.`. The ticket has actually been created when I go to tickets.

Also, when I go in to the ticket to add a comment, the same error appears. Again, the comment has been created.

Any ideas?

*** I hadn't set my SMTP email up in the env file correctly, it works as expected now.

**Comment by BadChoice** [comment]
Did you solve it?

**Comment by AugmentBLU** [comment]
Yes it was due to not having the SMTP settings completed in the env file. I was too quick in wanting to see how what options etc were available and didn't setup the SMTP fully. Works well. Thanks!
