### ISSUE TITLE
Slack invite not working

### ISSUE THREAD

**Issue by marktopper** [BadChoice/handesk#148]
FYI: Slack invite is not working

**Comment by BadChoice** [comment]
New "never expiring" link 

https://join.slack.com/t/handesk/shared_invite/enQtMzg4MzE4ODcwNzg2LWM5ODU5NDNlNGNkYmM0NzY5NGRlZjRkZDhjZmI2NTQ3NjY3Y2RkZjI1NTgwMzJiMzAzNTcxNDFmYzE5ZjQxNTY
