### ISSUE TITLE
Some who self triggering loop of Ticket Update Notifications

### ISSUE THREAD

**Issue by marco-aa** [BadChoice/handesk#15]
My mailbox was filling it self with "Ticket updated: #15:" over and over ;)

Not sure why - it looks like the messages send for update trigger them self a the next cron.

I was using the dev branch.

_https://github.com/BadChoice/handesk/blob/dev/app/Notifications/NewComment.php_

maybe related to

**Comment by BadChoice** [comment]
the ticket updated email is sent to the requester, to team and to admins, so if you are all, you'll get three emails with the same, could it be the thing?

The other thing is that your mail fetcher is not deleting the messages once downloaded (can you check that?)

Or are you using the same mailbox to send the update and to fetch?

**Comment by marco-aa** [comment]
The sender is someuser@somedomain.com

MAIL_USERNAME=support@ourserver.com
MAIL_FETCH_USERNAME=support@ourserver.com

Admin Email is support@ourserver.com
Team Email is support@ourserver.com

Do you think this setup is bad ?

**Comment by BadChoice** [comment]
Yes, since it will enter a infinite loop, ticket updated mail, its fetched and sends another mail, fetched again... and so on, you ahould have a email user just for incoming tickets, so all your support is done trough handesk

**Comment by marco-aa** [comment]
Ah ok - gracias! 

Should we mention this in the read.me as best practice ? If yes i can put it in the next PR ;)

**Comment by BadChoice** [comment]
Sure if you want, there is no harm in adding this note
Thank you so much
