### ISSUE TITLE
"composer install" step failed

### ISSUE THREAD

**Issue by antvet** [BadChoice/handesk#150]
So I'm trying to install Handesk on an Ubuntu 16.04 with php 7.1 and MySQL (version: 5.7.22-0ubuntu0.16.04.1). I followed the steps of the readme.md and I cloned the git in my /var/www/html. Everything worked great but when I tried to do the `composer install` I got [this error](https://zupimages.net/up/18/27/70oz.png). So I tried to install the missing package and I got [another error](https://zupimages.net/up/18/27/y5ln.png) with other missing packages (php-curl, php7.1-mbstring and php7.1-xml). After installing all these packages, I finally got [this error](https://zupimages.net/up/18/27/o8o2.png) during the `composer install`. Can you help me please? I don't know what to do now.

**Comment by BadChoice** [comment]
Looks like something with zip related?

Quick google search says that you need to install it 

`apt-get install php-zip`

Let me know if it worked!

https://stackoverflow.com/questions/41274829/php-error-the-zip-extension-and-unzip-command-are-both-missing-skipping

**Comment by antvet** [comment]
It worked. Thanks!
