### ISSUE TITLE
Can I use jQuery on handesk?

### ISSUE THREAD

**Issue by amax-123** [BadChoice/handesk#152]
Hi,

Is there a standard way I can use jQuery on handesk or we have to use standard js?
I see the jQuery tagsinput being used but how to use jQuery for my own customization? Should I just include it in the layout?

thanks

**Comment by joveice** [comment]
Not sure I entirely understood what you want. But if you link the jQuery assets here [app.blade.php#L32](https://github.com/BadChoice/handesk/blob/dev/resources/views/layouts/app.blade.php#L32) you can use it on all the pages, or you can link it etc here [show.blade.php#L67](https://github.com/BadChoice/handesk/blob/dev/resources/views/tickets/show.blade.php#L67) if you only want it for a specific page.

**Comment by BadChoice** [comment]
jquery is already there and can be used, actually it is used in lots of views
