### ISSUE TITLE
No emails on new tickets for supporting crew

### ISSUE THREAD

**Issue by lucidlemon** [BadChoice/handesk#154]
I don't get emails notifying me that I have a new ticket. The requester does get a mail but the support team (2 users) don't get any. Log file is empty/not even created and the users have all notifications active.

any idea what might have happened here?

**Comment by lucidlemon** [comment]
you mean sending an email from my support@domain.com to support@domain.com ?

**Comment by BadChoice** [comment]
yeah, or through the api using the support@domain.com as a requester

**Comment by lucidlemon** [comment]
okay will test.

btw: the usage of https://github.com/BadChoice/handesk-php could include some info on where to initiate the correct api key etc. it seems like it is more or less hardcoded currently, i think reading the api key from the .env file would be an improvement, but I guess i will open an issue there.

**Comment by BadChoice** [comment]
Yeah.. hehe that would be an improvement,
actually in my apps I init it like this 

Handesk::setup(config('services.handesk.url'), config('services.handesk.token'));

in the `AppServiceProvider` boot method and I put the url and token at config.services file, and of course, there it fetches from the env

```
    "handesk" => [
        "url"   => env('HANDESK_URL', "http://handesk.dev/api"),
        "token" => env("HANDESK_TOKEN", "the-api-token")
    ],
```

**Comment by lucidlemon** [comment]
okay so I created that ticket via the web page itself.

I got this mail in response onto support@..

```
##- Please type your reply above this line -##

Ticket updated
Daniel Test
2018-08-07 06:46:01

@import url('https://fonts.googleapis.com/css?family=Lato:300,500');
body {
margin: 20px;
font-family: Lato, sans-serif;
font-size: 14px;
line-height: 1.42857143;
font-weight: 100;
}
```

However both agents, which use different emails, did not get an email.

**Comment by BadChoice** [comment]
ok, that's something...
Gonna check why the style is writted there..

BTW I updated the handesk-php documentation with the init instructions

**Comment by lucidlemon** [comment]
any idea what could be wrong here?

**Comment by lucidlemon** [comment]
Any progress? The application is pretty much useless if it doesn't notify me about support messages.

**Comment by baggamsantosh** [comment]
Hi @lucidlemon @BadChoice 

I merged the dev branch to my master and tried by sending an email to my support.

This isn't still working. Can someone help me out here.

Thanks
