### ISSUE TITLE
Suggestion / Request: use Dependabot to keep dependencies up-to-date

### ISSUE THREAD

**Issue by greysteil** [BadChoice/handesk#172]
First of all, thanks for Handesk!

I've got a suggestion / request: would you be up for using [Dependabot](https://dependabot.com) to automatically create dependency update PRs for this repo? I ran it against my fork and it generated [these PRs](https://github.com/greysteil/handesk/pulls). I'll port the `laravel/framework` PR over to this repo now.

I built Dependabot and give it away for free to open source projects (partly for the exposure, but mainly because it feels good to give back and because the feedback is incredibly useful). I'm honestly only suggesting it because I hope it can save you some time doing work that is otherwise monotonous.

If you do decide to give Dependabot a go the easiest URL to add it from is [here](https://github.com/marketplace/dependabot). I'd love any feedback.

:octocat:

**Comment by BadChoice** [comment]
Hey!
Thank you so much for the PR, and for the Dependanbot info, it looks really good :D
I believe it we can realy use it in handesk as it is a side project and some updates are not done at the moment.

Thanks!

**Comment by greysteil** [comment]
Awesome, thanks @BadChoice 🎉
