### ISSUE TITLE
Can't view uploaded files / images

### ISSUE THREAD

**Issue by joveice** [BadChoice/handesk#184]
Is this a known issue? I can see the files but when I try to view them in web I get a 404 on a path that doesn't look like it exists

**Comment by BadChoice** [comment]
This doesn't happen in my environment neither in the test one,
can you check if the file has been uploaded through the filesystem?

**Comment by joveice** [comment]
Yea, they are uploaded

**Comment by vicenthy** [comment]
I was with the same error here I ran **php artisan storage:link** and it worked
