### ISSUE TITLE
[API] Class handesk not found 

### ISSUE THREAD

**Issue by w33haa2** [BadChoice/handesk#186]
"Handesk::setup(config('services.handesk.url'), config('services.handesk.token'));" if this line of code is added on AppServiceProvider the error will occur where I can import the handesk class?

**Comment by BadChoice** [comment]
You need to import Handesk in the AppServicoeProvide class itself

`use BadChoice\Handesk\Handesk;`

or directly use the namespaced one

`\BadChoice\Handesk\Handesk::setup(config('services.handesk.url'), config('services.handesk.token'));`
