### ISSUE TITLE
Question about pull requests

### ISSUE THREAD

**Issue by marco-aa** [BadChoice/handesk#20]
Hello :)

i'm using my fork to work on (local pc to my github forke) of your project.
Every thing fine about this.
If i make changes i push them into my forke and than i make a PR at your side - fine too ;)

Problem now is how to update my fork with you latest changes ? 
I use this https://stackoverflow.com/questions/3903817/pull-new-updates-from-original-github-repository-into-forked-github-repository/30343766#30343766

But sometimes my forked git does not show "switching the base".

Some idea what i'm doing wrong ? Thx !

p.s. i tried check this too https://www.sitepoint.com/quick-tip-sync-your-fork-with-the-original-without-the-cli/
at the moment my master does not contain app/Language.php for example

**Comment by BadChoice** [comment]
You just need to add a remote (of my branch and you can call it upstream)
then, you just need to 

`git pull upstream master` or `git pull upstream dev`

**Comment by marco-aa** [comment]
Ahh ok differnt way :-) i'll give it a try - Thanks

**Comment by marco-aa** [comment]
Ok this will work,

If someone is using the gitlab web-ui "compare across fork" will do the trick if "switching the base" it not showing up.

Maybe you need to 1-2 times change the head so you are in your fork and your pull request and your repository is the 1st with your branch and the 2nd is the one you have forked from :-)
