### ISSUE TITLE
HANDESK CONFIG: NEW TICKET FROM EMAILS

### ISSUE THREAD

**Issue by CarlosVillagra** [BadChoice/handesk#206]
Hi, everybody,

Im new handesk user. So i have a question, i think it is a silly one but i just cant figure out, so we’re going to appreciate if you could help us.

Well!, we were trying you awesome Helpdesk platform, which it is great, and fit to our needs. But after installing, and configuring it, we realize that when we send an email to our support email account, the Handesk does not create the new ticket.

I read: Email polling (new tickets and tickets updates) and we understand that this feature make possible that when a costumer send us an email to out support email the system create and open a new ticket or it isnt?.

Could you help us.

Thank in advance,

**Comment by BadChoice** [comment]
Yeah, that is exactly what it does,
you just need to setup your .env file with your email details and then add the cron to your server so it can be exectued every x minutes

```
* * * * * php /path-to-your-project/artisan schedule:run >> /dev/null 2>&1
```

**Comment by CarlosVillagra** [comment]
Hi, 

I appreciate you anwers, but it does not work.. below i pasted the config that i put into the  .env file, please could you take a look ant tell me what could it be wrong :

MAIL_HOST=mail.cccccc.com
MAIL_PORT=26
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null

MAIL_FETCH_HOST=mail.cccccc.com
MAIL_FETCH_PORT=110
MAIL_FETCH_USERNAME=helpdesk@cccccc.com
MAIL_FETCH_PASSWORD=Abcdef2018/*/
MAIL_FETCH_OPTIONS=/pop3
MAIL_FETCH_USE_SSL=true
// for options check https://secure.php.net/manual/de/function.imap-open.php

and this is the cron job i config in my cpanel: 
* * * * * php  /home/cccccc/public_html/soportest/handesk/artisan/artisan.php  schedule:run >> /dev/null 2>&1

When i create and update a ticket via the principal panel the system send the email, the only thing that does not work or better: I cannot make it works: is the creation of ticket via the emails.

Regards.

Carlos.

**Comment by BadChoice** [comment]
Looks like this is a email configuration issue which I can't really help.. 
Try playing arround with the config values..
