### ISSUE TITLE
adjust language

### ISSUE THREAD

**Issue by vicenthy** [BadChoice/handesk#208]
![image](https://user-images.githubusercontent.com/3986111/49442529-e6021100-f7b0-11e8-97fa-590675bcfb77.png)

I could not find which snippet of code renders that part of the image.

Can someone help?

**Comment by vicenthy** [comment]
I was able to locate is a component of the thrust library, I had to change the lib to work the language

**Comment by BadChoice** [comment]
Thank you! already approved the other PR, will update it as soon as I finish a metrics feature I'm adding
