### ISSUE TITLE
Team ticket overview

### ISSUE THREAD

**Issue by Onurrr** [BadChoice/handesk#221]
`SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'team_id' in where clause is ambiguous (SQL: select count(*) as aggregate from `tickets` inner join `memberships` on `tickets`.`team_id` = `memberships`.`team_id` where `memberships`.`user_id` = 2 and `status` < 4 and `team_id` = 2 and `tickets`.`deleted_at` is null) (View: handesk/vendor/badchoice/thrust/src/resources/views/index.blade.php)`

Getting this error when a ticket is assigned to a team (id 2 in this case), using an account that is in team (id2) and browsing to /tickets?team_id=2

**Comment by Onurrr** [comment]
Browsing to /tickets?team=2 works perfectly fine, only happens when browsing to /tickets?team_id=2

**Comment by BadChoice** [comment]
Where is the link that leads you to tickets?team_id=? so I can try to fix it

**Comment by Onurrr** [comment]
> Where is the link that leads you to tickets?team_id=? so I can try to fix it

On the dashboard, in the tickets overview if you press the assigned team link

![image](https://user-images.githubusercontent.com/9193729/51393610-62ba3600-1b38-11e9-912c-352845446ad7.png)

**Comment by jdc1898** [comment]
I have tried to reproduce this error but can't.

I have two `teams`

1. Gold
2. Silver

The Gold team has 1 user in it.
The Silver team has 2 users in it.

From the dashboard page I clicked `teams` which is a link to /tickets
Then, I clicked the inbox icon which takes me to the team ticket overview page /tickets?team=2

I am not sure where `/tickets?team_id=2` is coming from?

Either way, when I overwrote the URL with `/tickets?team_id=2` the page loaded and showed the same ticket.

**Comment by pcr3** [comment]
it seems to be coming from /app/Thrust/Ticket.php , updated line 42 to team instead of team_id and it resolved the issue.

https://github.com/BadChoice/handesk/blob/dev/app/Thrust/Ticket.php#L42

**Comment by amar30kul** [comment]
Getting the same error url created is /tickets?team_id=1
Also if we click on the agent URL created is /tickets?user_id=2
This happens if the logged in user is not an admin.
![Capture2](https://user-images.githubusercontent.com/61556220/81074146-39c4dc80-8f06-11ea-8407-759498d6218b.JPG)
![Capture1](https://user-images.githubusercontent.com/61556220/81074156-3af60980-8f06-11ea-9102-86f721cc6a03.JPG)
