### ISSUE TITLE
Disable leads

### ISSUE THREAD

**Issue by jdc1898** [BadChoice/handesk#233]
Not sure if anyone else is interested, but we don't have a need for the `Leads` portion of the project. We have added a settings option to toggle the visibility of the section in the sidebar. 

@BadChoice Is this something I could add in?

**Comment by BadChoice** [comment]
There is already an option to disable them in 
`config/handesk.php`

or you can just set the environment variable `HANDESK_LEADS_ENABLED` to false in .env

it alswo works for:

HANDESK_ROADMAP_ENABLED and HANDESK_RATING_EMAIL_ENABLED

**Comment by cheoAlejo** [comment]
Greetings, is there a site with all this documentation ?

**Comment by jdc1898** [comment]
It isn’t listed explicitly in the documentation. I am working on a few things and will add a section to readme file to make it more clear in my PR.

**Comment by BadChoice** [comment]
I believe we could work with some docs as there are lots of things that are not explained and are really easy to setup/change

**Comment by cheoAlejo** [comment]
That'd be great.
