### ISSUE TITLE
how to fix Client error: `GET https://ticket.fullstackllc.net/api/tickets?requester=admin` resulted in a `422 Unprocessable Entity` response:{"error":"No query results for model [App\Requester]. in \var\www\handesk\vendor\laravel\framework\src\Illumina (truncated...)",

### ISSUE THREAD

**Issue by loveunCG** [BadChoice/handesk#234]
Greeting everybody.
I'm using BadChoice/handesk for my own ticketing system.
I think that is good open source project
When call api ticket using `GuzzleHttp\Client`, I'm getting error

 

    $username = $user->username;
            try {
                $tickets = [];
                $client = new Client(["headers" => ["token" => config('services.handesk.token')]]);
                $response = $client->get($this->url . "/tickets?requester={$username}&status=open");                
    
                if (200 == $response->getStatusCode()) {
                    $tickets = json_decode($response->getBody(), true)['data'];
                }
                return response()->json(['message' => 'fecthed!', 'data' => $tickets, 'response_code' => 1], 200);
            } catch (\Throwable $th) {
                \Log::info($th->getMessage());
    
                return response()->json(['message' => $th->getMessage(), 'data' => [], 'response_code' => 1], 201);
            }

Error is follow as

    {"message":"Client error: `GET https:\/\/ticket.fullstackllc.net\/api\/tickets?requester=admin` resulted in a `422 Unprocessable Entity` response:\n{\"error\":\"No query results for model [App\\\\Requester]. in \\\/var\\\/www\\\/handesk\\\/vendor\\\/laravel\\\/framework\\\/src\\\/Illumina (truncated...)\n","data":[],"response_code":1}

Im getting data via call api using postman.
Im not sure what is wrong.
I think currently there is incorrect api call 
at my handesk back-end  i can get any log.

`App\Http\Controllers\Api\TicketsController;`

this is my handesk back-end for fetch tickets

    public function index()
        {
            \Log::info('this is route name');
            $requester = Requester::whereName(request('requester'))->orWhere('email', '=', request('requester'))->firstOrFail();
            if (request('status') == 'solved') {
                $tickets = $requester->solvedTickets;
            } elseif (request('status') == 'closed') {
                $tickets = $requester->closedTickets;
            } else {
                $tickets = $requester->openTickets;
            }
            return $this->respond($tickets);
        }

**Comment by jdc1898** [comment]
It is because the query is not returning any data for the requestor.

**Comment by loveunCG** [comment]
Thanks for your help
