### ISSUE TITLE
Suggestion: Support different types (Trouble Ticket, Task, Outage)

### ISSUE THREAD

**Issue by jdc1898** [BadChoice/handesk#235]
It would be nice to have support for different types of tickets. A few example would be for supporting typical trouble tickets, tasks, and maybe outages. Maybe even severity levels.

The KPI's would need to follow as well so we could closely track mean time to resolution.

**Comment by BadChoice** [comment]
Yeah.. a ticket type sound like a really good feature, 
will work on it, I believe ticket types should be dynamic so everyone can create theirs

**Comment by jdc1898** [comment]
working on it now.
