### ISSUE TITLE
Improve lead created notification

### ISSUE THREAD

**Issue by BadChoice** [BadChoice/handesk#26]
Show the lead details there

**Comment by deleugpn** [comment]
What is a Lead? I noticed it has attributes as of a company, but I dont quite get the concept.

The helpdesk that I'm used to each requester belongs to a company. Those requesters are usually employees of those companies and we can report on companies tickets.

**Comment by BadChoice** [comment]
We needed a tool to track tickets, and to track leads, leads are possible customers (that are not customers yet) so that lead management is basically a company (person) details, and a tasks (actions to perform) to finally make it your customer.

The tasks can be things like call him on tuesday or, prepare the quotes etc..

About the requester companies, it sounds good, in fact, there is no requesters list right now, since in our case almost all tickets enter through api (our app) or through email
