### ISSUE TITLE
New Ticket Types

### ISSUE THREAD

**Issue by robov** [BadChoice/handesk#273]
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'color' cannot be null (SQL: insert into `ticket_types` (`name`, `color`, `updated_at`, `created_at`) values (Support, , 2019-04-15 13:02:55, 2019-04-15 13:02:55))

**Comment by minkbear** [comment]
I face this problem too.

**Comment by jdc1898** [comment]
I was not able to re-produce this error. Was it fixed?

**Comment by BadChoice** [comment]
It should be fixed yeah
