### ISSUE TITLE
Users endpoint

### ISSUE THREAD

**Issue by Mte90** [BadChoice/handesk#308]
I saw this ticket system and seems perfect for my needs.
The big problem is how to integrate my payment system to handesk when they pay.
Right now I have another helpdesk and they have endpoints to create users but this one miss this feature.
There are in case other ways to create users and disable the create accounts page?

**Comment by BadChoice** [comment]
You mean through api?
This should be pretty easy to add there

**Comment by Mte90** [comment]
Yes right now this endpoint is missing

**Comment by Mte90** [comment]
any updates?

**Comment by BadChoice** [comment]
Not yet, I've been working on other projects, however, feel free to submit a PR , this should be a really easy one

**Comment by Mte90** [comment]
So I think that I need to add here a new endpoint: https://github.com/BadChoice/handesk/blob/dev/routes/api.php#L7
Create a new file similar to: https://github.com/BadChoice/handesk/blob/3cacc4916a/app/Http/Controllers/Api/TicketAssignController.php
With a reference to: https://github.com/BadChoice/handesk/blob/3cacc4916a/app/Http/Controllers/Api/TicketAssignController.php

**Comment by BadChoice** [comment]
Yes!
that's the way :D
