### ISSUE TITLE
Slack invite link in readme.md is stale

### ISSUE THREAD

**Issue by joelwhitehouse** [BadChoice/handesk#389]
Attempting to join slack says: "This invite link is no longer active."

**Comment by BadChoice** [comment]
readme updated with the new link

https://join.slack.com/t/handesk/shared_invite/enQtMzg4MzE4ODcwNzg2LTlmZTk4NGRjZDA5N2ExYTI2ZDhhNzAyOThmMDM1YjgwZTMzZTQ5ZjkxNDVlNzIwY2ZkZWExN2U2NDUwNWFiOWU
