### ISSUE TITLE
Parse error: syntax error, unexpected '@' 

### ISSUE THREAD

**Issue by lhenriksson** [BadChoice/handesk#40]
After I the installation I get the error message "Parse error: syntax error, unexpected '@'".
Full error message can be viewed at http://desk.lhenriksson.se/tickets

Looks like maybe a problem with the blade template?

Or have I made something stupid? :)

**Comment by marco-aa** [comment]
Hello @lhenriksson i get your login page only http://desk.lhenriksson.se/tickets.
Can you set in the .env APP_DEBUG=true and post a the trace ?

**Comment by BadChoice** [comment]
it is the same error Travis CI gives when passing tests, 
Yesterday we got a PR fixing a missing @ in the `sidebar.blade.php blade` so maybe it fixes it, can you try to pull the last commit from the master branch?

**Comment by lhenriksson** [comment]
Oh, missed that you can get to the login page, it's after the login the error appears.
It's the default login credentials.

i will try to pull the latest commit.

**Comment by BadChoice** [comment]
the other thing you can quickly try, is to get the `sidebar.blade.php` file and start removing lines, until it works, so we can know what line does make it fail

I believe it has something to do with the php version as well, since it is not failing on my dev machine, neither on our prod server

**Comment by deleugpn** [comment]
Probably fixed by https://github.com/BadChoice/handesk/pull/37

**Comment by BadChoice** [comment]
I think it is fixed now! just pull the last version

**Comment by lhenriksson** [comment]
It worked perfect! :)
