### ISSUE TITLE
Create ticket without authentication

### ISSUE THREAD

**Issue by cherif-bayo** [BadChoice/handesk#401]
Is it possible for users to create ticket without authentication ?

**Comment by BadChoice** [comment]
Yes, with email or through the api

**Comment by cherif-bayo** [comment]
How is it possible with email ?

**Comment by BadChoice** [comment]
In the readme is explained, basically you can configure an email account to check, and handesk will check that email each minute to fetch new emails and convert them as tickets

```
Email pulling
Enter your mail credentials in .env

MAIL_FETCH_HOST=pop3.handesk.com   
MAIL_FETCH_PORT=110   
MAIL_FETCH_USERNAME=hello@handesk.com   
MAIL_FETCH_PASSWORD=secret-password   
```

**Comment by cherif-bayo** [comment]
Oh good. Gonna give a try to this on my local machine before production ;) .
Thanks a lot for Handesk
