### ISSUE TITLE
Bump php version for docker

### ISSUE THREAD

**Issue by Mte90** [BadChoice/handesk#408]
I had to edit the dockerfile to use php 7.2.5 because some of the composer dependence created issue and wasn't impossible running the image.

**Comment by BadChoice** [comment]
can you send a PR? I'll merge ASAP

**Comment by Mte90** [comment]
Before to do that I prefer another check just to be sure that is not me with docker.
I saw some conflicts with newrelic and xdebug so I just removed.

**Comment by BadChoice** [comment]
Ok! I have 0 knowledge of docker so I'm afraid I can't help here hehe

**Comment by Mte90** [comment]
I have too but to contribute in this project is required...

**Comment by Mte90** [comment]
Also looking at the various pr to this project there are different dependencies bump to do anyway.
