### ISSUE TITLE
Branch strategy

### ISSUE THREAD

**Issue by deleugpn** [BadChoice/handesk#41]
Should contributors use dev branch for pull requests and master branch be protected for releases only?

**Comment by BadChoice** [comment]
well, hotfixes can be merged to master as well

**Comment by BadChoice** [comment]
I updated the default branch to be the dev, so new PR will be automatically sent there if not specified otherwise

**Comment by deleugpn** [comment]
Looks good. Let's see how it feels moving forward and we can reopen this if anything else needs assessment.
