### ISSUE TITLE
PSR-2

### ISSUE THREAD

**Issue by deleugpn** [BadChoice/handesk#45]
![Image](https://images-cdn.9gag.com/photo/aRQneE2_700b.jpg)

Believe it or not, I'm all #teamBracesInSameLine (second type). Unfortunately that's not the path that [PSR-2 chose](http://www.php-fig.org/psr/psr-2/).

After working with some open sources projects (and Laravel source code itself), I learned to _deal with it_. PSR-2 does make code more readable from a world-wide perspective. If you get used to reading PSR-2 formatted code, you can read anybody's PSR-2 formatted code in the world.

Anyway, the point of this topic is to say I hope you guys don't mind my PRs with PSR-2 code-style. PHPStorm will automatically format code for me that way.

**Comment by BadChoice** [comment]
Hahaha, yeah I'm using a really big indentation to make the code breath, and make me feel wasted when a file starts growing so much, so I prefer using the { inline to avoid a bit of that big spacing,

I know laravel uses the PSR-2 approach but I'm not really into it yet..

**Comment by marco-aa** [comment]
Hi all,

i good in contact with php-cs-fixer from another project (https://mattstauffer.co/blog/using-php-cs-fixer-to-fix-up-your-php-code/) mabye we can use it ? 
I can add it an make a PR ?

**Comment by BadChoice** [comment]
Ok sounds good, lets do it and see how it looks

**Comment by marco-aa** [comment]
Ok first try first loose ;)

php-cs-fix need sebastian/diff 1.4.x at the moment it's not working with sebastian/diff 2.x. see 
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2962

I guess we locked sebastian/diff to 2.x because of phpunit 6.3.

So i see 3 ways
1) install php-cs-fix local and global 
2) downgreat packages so we can use sebastian/diff 1.4.x
3) wait for php-cs-fix to work with sebastion/diff 2.0 

I recommend 3) over 2) over 1) :)

**Comment by deleugpn** [comment]
Why not just go for StyleCI?

**Comment by marco-aa** [comment]
hmm "This package is abandoned and no longer maintained. No replacement package was suggested." i got on packagist.org ...

Short info ... i runned php-cs-fixer local and it's working fine - made files PSR2 conform  - so just in case your editor or yourself use diffrent formats - the git will get PSR2 :-)

**Comment by deleugpn** [comment]
StyleCI.org

**Comment by BadChoice** [comment]
Just enabled it, but it tries to fix ide_helper.php too... i guess it is configurable right?

**Comment by BadChoice** [comment]
I tried to apply the style.ci PR but it makes the test fail

https://github.com/BadChoice/handesk/pull/49

I guess something is messed up, if anybody wants to play with the configuration.

It is the 

`.styleci.yml` file

(I realy like to align the equals and arrays, so please, don't change that 😛 )

**Comment by SpacePossum** [comment]
`styleci` uses `php cs fixer` and brings some more.
However it means it inheritances some issues for `php cs fixer` itself ;)

If you want to go for `styleci` and the `help wanted` label is still current I can ping the author here for you.

If you go for `php cs fixer` I'm happy to inform you that I'm resolving the `diff 1.4 vs 2.0` ATM.
Let me know if you've other questions about `php cs fixer`, happy to answer those!

**Comment by BadChoice** [comment]
Hi @SpacePossum yeah, this issue and lavel is still current, 
I'm really new into that PSR stuff so I have really 0 idea on how styleci really works so any help will be really appreciated and sure worth the learning,

**Comment by BadChoice** [comment]
Style ci working :)
