### ISSUE TITLE
Support for attachments / pictures

### ISSUE THREAD

**Issue by marco-aa** [BadChoice/handesk#5]
Dear Team,

do you have support for attachments / pictures ? I tried to find it in the migrations but i couldn't find it ;)

Thanks 
MarcO

**Comment by BadChoice** [comment]
Hi Marc, is is still not there, but it will ;)

Thanks for the issue, just stay tuned to this issue to see any progress, or do a PR if you will 

Cheers,

**Comment by marco-aa** [comment]
Thanks for your quick feedback,

today i looked around to find a imap laravel bundel for attachments ... while reading issues in this bundels i found https://github.com/message/php-mime-mail-parser/blob/master/lib/MimeMailParser/Parser.php  - it seems to be solid ;)

This looks interessting - give the Email to this parser as written it the read.me and you can iterate trough all attachments - this could be saved in a detail table for the email you got over your imap interface and the views can be extended to show possible attachments to an email - so my first idea.

**Comment by BadChoice** [comment]
Thank you! looks rally great,
I'll work on it today

**Comment by marco-aa** [comment]
One more i found out at https://github.com/ddeboer/imap 
I used this with a thunderbird email html with a picture and a picture as a attachment. With this library i only got the attachment but not the embedded picture inside the email-html-text.
I thinks there is (still) a bug - and i think a lot of customers/users will embedd images in this way.

Today morning a had a look at https://github.com/barbushin/php-imap. This will only need imap enabled and does not need pecl additional parser addons installed. With this one i could download all attachments - so i would give this a first try bevor the others onces.

**Comment by BadChoice** [comment]
I got it working, check the `dev` branch if you wanna play arround

if you already have it installed you need to

```
php artisan migrate
mkdir storage/app/mail_attachments
mkdir storage/app/public/attachments #if using the local driver
php artisan storage:link #if you use the local driver
```

> Note that it will use the Laravel filesystem options to store the attachments, so attachments will be stored in `/attachments` folder in the filesystem root

Now it only misses that user can upload attachments to leads/tickets from the backend

**Comment by marco-aa** [comment]
Wohhhh :) great !

I'm at the moment playing around with handsek and  i'll test the switch to dev branch today  / tomorrow :)

**Comment by BadChoice** [comment]
Added the "attach file" option to ticket comment and leads status update, so the issue is done
