### ISSUE TITLE
Portuguese Language Support

### ISSUE THREAD

**Issue by rpaggi** [BadChoice/handesk#57]
Hi!

I'm interested on this project, and I'm thinking to contribute adding the Brazilian Portuguese language.

Soon I'll send my PR.

Best regards!

UPDATE:
Translate status: ⚫⚫⚫⚫⚫⚫⚫⚫⚫⚫⚫⚫ 100%

**Comment by BadChoice** [comment]
Thank you! It will be really appreciated!

**Comment by rpaggi** [comment]
Suport to Brazilian Portuguese added at PR #73
