### ISSUE TITLE
Attachments not downloadable

### ISSUE THREAD

**Issue by mathiasmadsen** [BadChoice/handesk#579]
I discovered an issue when opening attachments that are not images. The links would go to an url like 'http://127.0.0.1:8000/storage/attachments/{{filename.ext}}/login' or 'http://127.0.0.1:8000/storage/attachments/{{filename.ext}}/tickets' (if logged in)

I saw this error on docx and ai files but I expect that all files that are not able to be shown directly in the browser would have this problem.

My solution was to add the following route in **web.php**
<pre>
Route::get('attachments/{file_name}', function($file_name = null)
{
    $path = storage_path().'/app/public/attachments/'.$file_name;
    if (file_exists($path)) {
        return Response::download($path);
    }
})->name('attachments');
</pre>

and to update line 8 of the **attachment.blade.php** to:
<pre>
< a href="{{ route('attachments', $attachment->path) }}" target="_blank">{{ $attachment->path }}</a >
</pre>

**Comment by BadChoice** [comment]
Thank you! Gonna add it to the project

**Comment by BadChoice** [comment]
Just implemented it

https://github.com/BadChoice/handesk/commit/3a89f924b70f87523a2bb5d3bd524bc305bf11e0

I made that if the file is image, pdf or video it still displays the link url so we can open it in the browser, and if not, then it will download it
