### ISSUE TITLE
reply to solved tickets can get lost 

### ISSUE THREAD

**Issue by marco-aa** [BadChoice/handesk#58]
To-Reproduce:
Customer sends email 
Will get notification about ticket created - fine :)
Supporter is writing answer and mark ticket as solved.

Customer don't think so and will reply 

Supporter will not se the reply because it's listed under solved ... this will be a little show stopper ;) 
Support will not react ...

Version:
current master

Possible solution:
if ticket is in solved list and customer replys ticket will get back to pending state 

Maybe related to issue #22

**Comment by BadChoice** [comment]
Yes, makes totally sense,
I will make that if customer replies when it is solved, it will be marked as open again (since pending means is waiting for customer)

**Comment by marco-aa** [comment]
Thanks !

**Comment by marco-aa** [comment]
I pulled the dev and checkt app/Ticket.php so i could be sure to work with the fixed verison :)

Then i tried the steps i discribed but the ticket status did not change. Some idea why ?

**Comment by BadChoice** [comment]
Can you try to create a test in similar at the `SimpleTicketTest::commenting_a_closed_ticket_reopens_it` 

but in 

`CreateTicketsFromNewEmailsTest`

Should be a mix of that test and the `does_create_comments_for_new_comment_emails`

I have to finish another thing now so I can't look at it quickly..

Let me know!

**Comment by BadChoice** [comment]
Hi,
Just created the test

`CreateTicketsFromNewEmailsTest::a_comment_from_requester_email_changes_status_to_open`

And it passes,

What it testes is that:

1. Customer creates a ticket,
2. Agent mark it as solved
3. Customer replies by email
*4. Ticket is reopened*

**Comment by marco-aa** [comment]
Thanks - i looked at the tests you mentioned - but yesterday i run in problems with phpunit on my dev machine ;)
I'll be on the road up to monday - so i'm not sure if i found the time for a closer look - i'll try to bring up the tests the on the server ASAP and check if / whats going on :-)

**Comment by BadChoice** [comment]
I believe it should be working now, but let me know if it is not for you

Cheers,

**Comment by marco-aa** [comment]
Hello BadChoice :)

if found out 
`PHP Fatal error:  Trait 'Illuminate\Foundation\Testing\RefreshDatabase' not found in /home/forge/...../tests/Unit/CreateTicketsFromNewEmailsTest.php on line 18
`
Did i forget to run a command because
`vendor/laravel/framework/src/Illuminate/Foundation/Testing` does not contain RefreshDatabase 
or is a file not checked in ?

**Comment by BadChoice** [comment]
you need to `composer update`

**Comment by marco-aa** [comment]
Thanks @composer - now it works ...

Customer writes Email
Customer gets Notificaiton
Supporte (wich is currently logged in) is writing a answer **and not assigning and pressing comment as solved** 
Customer gets this answer
Customer writes back 
**ticket still remains solved**

I guess i could be because of this workflow ?

```
 ./vendor/bin/phpunit --filter CreateTicketsFromNewEmailsTest tests/Unit/CreateTicketsFromNewEmailsTest.php
PHPUnit 6.3.0 by Sebastian Bergmann and contributors.
...                                                                 3 / 3 (100%)
Time: 659 ms, Memory: 10.00MB
OK (3 tests, 15 assertions)
```

**Comment by marco-aa** [comment]
Ok i digged into to it the old way ... via writing into logfile ;)

Change source :
```
    private function updateStatusFromComment($user, $newStatus) {
        Log::info('$newStatus: '.$newStatus);
        Log::info('$this->status: '.$this->status);
        $previousStatus = $this->status;
        if ($newStatus && $newStatus != $previousStatus){
                $this->updateStatus($newStatus);
                 Log::info('A');
        }
        else if (!$this->user && $this->status != static::STATUS_NEW){
                $this->updateStatus(static::STATUS_OPEN);
                Log::info('B');
        }
        else{
                $this->touch();
                Log::info('C');
        }

        event(new TicketStatusUpdated($this, $user, $previousStatus));
        return $previousStatus;
    }
```

After i set the ticket to solved i wrote a email from the custer account and found in the logfile

```
[2017-09-19 12:22:20] production.INFO: $newStatus:
[2017-09-19 12:22:20] production.INFO: $this->status: 4
[2017-09-19 12:22:20] production.INFO: C
```
$newStatus from  public function addComment($user, $body, $newStatus = null) seams to be null

I try to go mor into it later this day or tomorrow ;)

**Comment by BadChoice** [comment]
I can't work on this today, let me know what else you find and tomorrow I can spend some time ;)

**Comment by marco-aa** [comment]
I'm not sure if this line is resonsible for reOpen 
`if (!$this->user && $this->status != static::STATUS_NEW){`

and i guess $this->user is set because ticket was once send to customer by a support-user ?
so touch() block will be triggered....

**Comment by BadChoice** [comment]
You were right, I was looking for the ticket user, and I needed to look for the commenter

Fixed in the last commit

**Comment by marco-aa** [comment]
Thanks a lot that you took the time :-)

**Comment by marco-aa** [comment]
Worked like charme :-)

**Comment by BadChoice** [comment]
Great!

**Comment by dineshsarak77** [comment]
is there any email reply system in handesk

**Comment by BadChoice** [comment]
it replies automatically when you update the ticket
