### ISSUE TITLE
enhancment: default tempalte for issues

### ISSUE THREAD

**Issue by marco-aa** [BadChoice/handesk#59]
Inspired by the rocket.chat team - the use a tempalte if somebody is filling out an isssue -
makes it easyer for the dev's to reproduce - maybe usefull for handesk too ???
Every time you open an issues in the write-tab you will see the text from the bottom 

# # # # # # # #

### Server Setup Information:

* Version of handesk:
* Operating System:
### Steps to Reproduce:

1. 
2. 
3.

**Comment by BadChoice** [comment]
This is a good one but I think we don't need it yet, 
When the project has more "non dev" users then it will really make sense but right now, there are really minor bugs

**Comment by marco-aa** [comment]
Ok so i'll close it - so long ;)
