### ISSUE TITLE
Enable self signed certificates in smtp out / swiftmailer

### ISSUE THREAD

**Issue by marco-aa** [BadChoice/handesk#6]
Dear @BadChoice ,

i made a fork to add support to laravel swiftmailer to use smtp out on a self signed certificate (have done this for a other project too).

Into to .env i'll add
```
MAIL_SSLOPTIONS_ALLOW_SELF_SIGNED=true
MAIL_SSLOPTIONS_VERIFY_PEER=true
MAIL_SSLOPTIONS_VERIFY_PEER_NAME=false
```

Into config/mail.php i'll add (with default secure settings)
```   
'stream' => [
        'ssl' => [
            'allow_self_signed' => env('MAIL_SSLOPTIONS_ALLOW_SELF_SIGNED', false),
            'verify_peer' => env('MAIL_SSLOPTIONS_VERIFY_PEER', true),
            'verify_peer_name' => env('MAIL_SSLOPTIONS_VERIFY_PEER_NAME', true),
        ],
    ], 
```

So swiftmailer will use this features for open-ssl-socket-connections.
I found this solution on a laravel forum ;)

For my PR should i work an dev or master ? Should i take care about a special workflow ?

**Comment by BadChoice** [comment]
sure, send me the PR and I'll merge it
