### ISSUE TITLE
Integrity constraint violation: 1048 Column 'name' cannot be null

### ISSUE THREAD

**Issue by marco-aa** [BadChoice/handesk#63]
Today the polling of emails stopped working.

I checked the log files and found a DB Exception i guess the Email from the customer is correct but it did not contain a Name.

`Next Illuminate\Database\QueryException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'name' cannot be null (SQL: insert into `requesters` (`email`, `na
me`, `updated_at`, `created_at`) values (xxxxxxxx@yyyyyyyy.net, , 2017-09-19 07:51:02, 2017-09-19 07:51:02)) in /home/forge/....../vendor/laravel/framework/src/
Illuminate/Database/Connection.php:647`

**Comment by BadChoice** [comment]
Nice one hehe, we have two options

- Put a default name if none in the email
- Make the `name` nullable

**Comment by marco-aa** [comment]
I guess nullable is fine.

A default like "unknow" can cause a reply by a support - who i reading the name - like "Hello my Unknow" 
So better nullable i think

**Comment by marco-aa** [comment]
Hello again ;)

the error occurt again in production - at the moment as a workaround i test

 ` alter table requesters modify name varchar(191) null;`

if you think we leave the field nullable (side effect with forms and objects ???)

i can make a migraion to fix this error. What do you think ?

**Comment by BadChoice** [comment]
ops, 
yes please, I'll merge it;, make it nullable and we will be ready to go :D

**Comment by BadChoice** [comment]
Just fixed this!

**Comment by saam-khatri** [comment]
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'email' cannot be null (SQL: insert into `contacts` (`name`, `email`, `subject`, `massage`, `updated_at`, `created_at`) values (saam, , shie, , 2019-01-19 12:05:50, 2019-01-19 12:05:50))

how can i fix this problem

**Comment by BadChoice** [comment]
Looks like email is required
How did you get this error, what did you do?

Jordi Puigdellívol

El 19 gen 2019, a les 13:08, saam-khatri <notifications@github.com> va escriure:

**Comment by brijesh138** [comment]
Column 'name' cannot be null

INSERT INTO `ci_crud` (`name`, `email`, `created_at`) VALUES (NULL, NULL, '21-01-06')

Filename: C:/xampp/php/htdocs/crud/crud_ci320/system/database/DB_driver.php

Line Number: 691
