### ISSUE TITLE
Feature: hide login email adress in reply emails to customer or set a default value

### ISSUE THREAD

**Issue by marco-aa** [BadChoice/handesk#66]
If a customer reciews a email he will get   supportername@company.com and a reply to support@company.com but in this way the suppername email-adress will spread around in the world ;)

Why not use "Supporter name <support@company.com>" in From and support@company.com in Reply-To field ? 

So we have a central account for the world and the support users can login with there emailadresses.

Maybe we can set this a optional flag ?

What do you think ?

**Comment by BadChoice** [comment]
It makes sense, let me discuss it with my team (who uses handesk in our company) and see if they believe it should be the default behavior as well

**Comment by marco-aa** [comment]
Great that you implemented it :-)

but i get a runtime error - 

`[2017-09-20 11:18:22] production.ERROR: Call to a member function author() on null {"userId":2,"email":"xxxx@yyyyyyy.com","exception":"[object] (Symfony\\
Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function author() on null at /home/forge/handesk.vikinks.com/app/Notifications/NewComment.ph
p:68)
[stacktrace]
#0 /home/forge/handesk.vikinks.com/app/Notifications/NewComment.php(59): App\\Notifications\\NewComment->shouldUseAgentName()
`

**Comment by BadChoice** [comment]
haha my bad, I did a typo..
Should be fixed now

**Comment by marco-aa** [comment]
Fixed :) Thanks a lot
