### ISSUE TITLE
SMTP Error when create new ticket

### ISSUE THREAD

**Issue by AmityTek** [BadChoice/handesk#737]
Hi,

I have this error when I create a ticket.
I don't understand why ...

**_Expected response code 250 but got code "550", with message "550 5.7.60 SMTP; Client does not have permissions to send as this sender "_**

Thanks

**Comment by AmityTek** [comment]
@BadChoice Any idea ? it's very important

**Comment by BadChoice** [comment]
This looks like something on you email server

**Comment by softhightech** [comment]
did you configured the smtp server in ".env" file?
