### ISSUE TITLE
create issue button

### ISSUE THREAD

**Issue by antton** [BadChoice/handesk#76]
If we don't use  bitbucket we should remove the button.

I change the issue.blade.php with the following line at the beginning
@if(strcmp(config('issues.credentials.key'),'the-bitbucket-key-if-using-oauth') !== 0)

and ending with an other 
@endif

I know that the condition is not really good but when I made the first copy of the .env.example is the string you had inside for credentials.key

Should be better to use a switch inside the .env and issue config file to check if we have any issue addon activated.

As I know that I'm not going to use it for now, I'll let it like that.

I'm not making any PR because It's now an optimal solution but at least my agents are not getting errors when they press the button ;)

Thanks for all!

**Comment by antton** [comment]
I get an error compiling ;)

Error compiling template

but I'm sure it is because I don't know how to use 'Blade' the laravel template system, I'll take a look how to do it properly.

Cheers!

**Comment by BadChoice** [comment]
I believe it is better to use

```@if( config('issue.credentials.driver') )``` 

and setting the driver to `null`

**Comment by BadChoice** [comment]
Oh, i've seen the if is already there

`@if( count( config('issues.repositories')) > 0)`

so you simply need to leave the issues.repositories empty at 'config\issues.php' file

**Comment by antton** [comment]
Hi, You are right! we already have the if there.

But if I have lo change the issues.php that by default is like this:

```
return [
    'driver'      => 'bitbucket',
    'credentials' => [
        'driver'        => env('BITBUCKET_DRIVER', 'basic'), //basic, oauth
        'key'           => env('BITBUCKET_KEY'),           //oauth
        'secret'        => env('BITBUCKET_SECRET'),        //oauth
        'user'          => env('BITBUCKET_USER'),          //basic auth
        'password'      => env('BITBUCKET_PASSWORD'),       //basic auth
    ],
    'repositories' => [
        'Xef Back'    => 'revo-pos/revo-back',
        'Xef App'     => 'revo-pos/revo-app',
        'Retail Back' => 'revo-pos/revo-retail',
        'Retail App'  => 'revo-pos/revo-retail-app',
        'Flow Back'   => 'revo-pos/revo-flow-back',
        'Flow App'    => 'revo-pos/revo-flow-app',
    ],
];
```

Do you mean to remove the credentials array? Don't you think is better to use another attribute to control the issues activation.

Let me know!

**Comment by BadChoice** [comment]
Just changing that file this way should be enough

```
return [
    'driver'      => 'bitbucket',
    'credentials' => [
        'driver'        => env('BITBUCKET_DRIVER', 'basic'), //basic, oauth
        'key'           => env('BITBUCKET_KEY'),           //oauth
        'secret'        => env('BITBUCKET_SECRET'),        //oauth
        'user'          => env('BITBUCKET_USER'),          //basic auth
        'password'      => env('BITBUCKET_PASSWORD'),       //basic auth
    ],
    'repositories' => [

    ],
];
```

But yeah, maybe putting the issues driver to env would be a better option

**Comment by antton** [comment]
That's what I did and it works, but I agree with the issue driver option!

**Comment by BadChoice** [comment]
Fixed in dev ;)

**Comment by antton** [comment]
Great!
