### ISSUE TITLE
Laravel 5.3 / 5.4

### ISSUE THREAD

**Issue by andriaripratama** [BadChoice/handesk#79]
Hi,

Is there any version with Laravel 5.3 or 5.4? Thanks

**Comment by BadChoice** [comment]
The dirst versions were on laravel 5.4, but the current one is only at 5.5

But 5.5 and 5.4 are so similar that maybe you can just change the dependency in composer.json and maybe it works without any other change

**Comment by andriaripratama** [comment]
Oh I see. Okay, I'll do change the Composer. Thanks for reply!
